Revert "adb: add transport benchmark."
This reverts commit ffb7c83ec7ba4f32c70c131eeb5f2f7b80529cbc.

Reason for revert: Breaks aosp-master renderscript and sdk_mac:
  error: system/core/adb/Android.bp:199:19: unrecognized property "host_supported"

Change-Id: Ifd75921dcdf5dce57f98833a913540914984b293